version: '3.8'
services:
    app:
        build: .
        image: transactions-app
        container_name: transactions-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - app-network
        dns:
          - 8.8.8.8
          - 8.8.4.4

    nginx:
        image: nginx:alpine
        container_name: transactions-nginx
        ports:
            - "3001:80"
        volumes:
            - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d
            - .:/var/www
        depends_on:
            - app
        networks:
            - app-network
        dns:
            - 8.8.8.8
            - 8.8.4.4

    db:
        image: mysql:8.0
        container_name: transactions-db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: default
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./docker-compose/data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - app-network

    db-test:
        image: mysql:8.0
        container_name: transactions-db-test
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: default
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./docker-compose/data-test:/var/lib/mysql
        ports:
            - 33060:3306
        networks:
            - app-network

networks:
  app-network:
    driver: bridge
